name: Auto Assign on Review

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add reviewer as assignee
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          const issue_number = context.payload.pull_request.number;
          const reviewer = context.payload.review.user.login;
          const review_state = context.payload.review.state;

          if (review_state === 'approved' || review_state === 'changes_requested') {
            await github.issues.addAssignees({
              owner,
              repo,
              issue_number,
              assignees: [reviewer]
            });
          }
