name: Add Reviewer as Assignee

on:
  pull_request_review:
    types: [submitted]

jobs:
  add-assignees:
    runs-on: ubuntu-latest
    if: |
      github.event.review.state == 'approved' || 
      github.event.review.state == 'changes_requested'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add assignees to issue
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REVIEWER: ${{ github.event.review.user.login }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/jameswolpe/actions_test/issues/${{ env.PR_NUMBER }}/assignees \
            -f "assignees[]=${{ env.REVIEWER }}"
