name: Auto Assign on Review

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-assign:
    if: github.event.review.state == 'approved' || github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add reviewer as assignee
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.github_token }}
          assignees: ${{ github.actor }}
