name: Add Assignees to Issue

on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  add-assignees:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Add assignees to issue
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/jameswolpe/actions_test/issues/2/assignees \
            -f "assignees[]=jameswolpe1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
