name: Add Reviewer as Assignee

on:
  pull_request_review:
    types: [submitted]

jobs:
  add-assignees:
    runs-on: ubuntu-latest
    if: |
      github.event.review.state == 'approved' || 
      github.event.review.state == 'changes_requested'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Reviewer and PR Number
        run: |
          echo "Reviewer: ${{ github.event.review.user.login }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
